import { Enum } from 'enum-plus';

export const Languages = Enum({
  am: { value: 'am', label: '阿姆哈拉语' },
  ar: { value: 'ar', label: '阿拉伯语' },
  bn: { value: 'bn', label: '孟加拉语' },
  de: { value: 'de', label: '德语' },
  en: { value: 'en', label: '英语' },
  es: { value: 'es', label: '西班牙语' },
  fil: { value: 'fil', label: '菲律宾语' },
  fr: { value: 'fr', label: '法语' },
  hi: { value: 'hi', label: '印地语' },
  id: { value: 'id', label: '印尼语' },
  ja: { value: 'ja', label: '日语' },
  km: { value: 'km', label: '高棉语' },
  ko: { value: 'ko', label: '韩语' },
  ms: { value: 'ms', label: '马来语' },
  my: { value: 'my', label: '缅甸语' },
  ne: { value: 'ne', label: '尼泊尔语' },
  pt: { value: 'pt', label: '葡萄牙语' },
  ru: { value: 'ru', label: '俄语' },
  sw: { value: 'sw', label: '斯瓦希里语' },
  th: { value: 'th', label: '泰语' },
  tr: { value: 'tr', label: '土耳其语' },
  ur: { value: 'ur', label: '乌尔都语' },
  vi: { value: 'vi', label: '越南语' },
  sq: { value: 'sq', label: '阿尔巴尼亚语' },
  az: { value: 'az', label: '阿塞拜疆语' },
  et: { value: 'et', label: '爱沙尼亚语' },
  eu: { value: 'eu', label: '巴斯克语' },
  be: { value: 'be', label: '白俄罗斯语' },
  bg: { value: 'bg', label: '保加利亚语' },
  da: { value: 'da', label: '丹麦语' },
  fi: { value: 'fi', label: '芬兰语' },
  ka: { value: 'ka', label: '格鲁吉亚语' },
  gu: { value: 'gu', label: '古吉拉特语' },
  nl: { value: 'nl', label: '荷兰语' },
  gl: { value: 'gl', label: '加利西亚语' },
  ca: { value: 'ca', label: '加泰罗尼亚语' },
  cs: { value: 'cs', label: '捷克语' },
  hr: { value: 'hr', label: '克罗地亚语' },
  af: { value: 'af', label: '南非荷兰语' },
  el: { value: 'el', label: '希腊语' },
  hy: { value: 'hy', label: '亚美尼亚语' },
  uz: { value: 'uz', label: '乌兹别克语' },
  'zh-TW': { value: 'zh-TW', label: '中文，台湾' },
  'zh-CN': { value: 'zh-CN', label: '中文，中国' },
} as const);
